Scripts / Atalhos {
    crlt + L Limpar a tela
    .exit - sair do programa
    typeof - mostra qual o tipo primitivo
    variavel.toFixed(2) - Declara a quantidade de casas do numero dentro do parenteses, no caso do exemplo seriam 2 casas a mais.
    variavel.toFixed(2).replace('.', ',') - Troca o ponto por vírgula
    n1.toLocaleString('pt-BR', {Style: 'currency', currency: 'BRL'}) - O valor ficar em Real brasileiro, se trocar a ultima abreviação por USD fica em Dolar ou EUR fica em Euro.
}

Escrever na tela - console.log(` ${} `)

Mostrar a data/hora/dia atuais:
var agora = new Date ()
var hora = agora.getHours() / // agora.getDay .get...  variavel.GETopção

mkdir - criar o nome
cd + nome - abrir o nome do arquivo

yarn init -y* cria o  arquivo - package.json 
Code . - abre o arquivo com VS
